name: 'Get Labels'
description: 'Get labels for PR'
author: 'fml09'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  repo:
    description: 'The name of the GitHub repository you want to get the labels.'
  owner:
    description: 'The owner of the GitHub repository you want to get the labels.'
  pull_number:
    description: 'The PR Number of the GitHub repository you want to get the labels.'

outputs:
  labels:
    description: 'Labels.'
runs:
  using: 'node12'
  main: 'dist/index.js'
